### ISSUE TITLE
RouteRegistry Deprecated. Any alternate way for RC4 version?

### ISSUE THREAD

**Issue by ganeshkbhat** [mgechev/dynamic-route-creator#4]
The RouteRegistry seems to have now been deprecated. Is there an alternate way of doing this in RC4 or newer versions?

**Comment by teone** [comment]
Looking for a solution in the released version, is this possible?

**Comment by mgechev** [comment]
You can use lazy loading with [the new router](https://angular.io/docs/ts/latest/guide/router.html), which also helps adding routes dynamically.
